#!/bin/sh

# Set common folder paths as aliases
shopt -s cdable_vars
export notes=$HOME/syncthing/notes
export docs=$HOME/syncthing/docs
export work=$HOME/syncthing/work
export logpath=$HOME/syncthing/log
export cabinet=$HOME/syncthing/cabinet/settings.json
export log=$logpath/cabinet/$(date +%Y-%m-%d)/LOG_DAILY_$(date +%Y-%m-%d).log

# Function: Edit a file in $notes with vim
vn() {
    if [[ -z "$1" ]]; then
        echo "Error: No argument provided"
        return 1
    fi

    # Strip '.md' if necessary
    filename="${1%%.md}"

    vim "$notes/$filename.md"
}

# Function: Retrieve the path of a file in $notes
n() {
    if [[ -z "$1" ]]; then
        echo "Error: No argument provided"
        return 1
    fi

    # Set the filename as a variable
    filename="$notes/$1.md"

    # Return the file path
    echo "$filename"
}

# Set ls options
alias ls='ls -hal --color'

# Show calendar
alias cal='cal -B1 -A1; echo -e "\nUse ncal to display horizontally"'
alias ncal='ncal -B1 -A1'

# Use vim as default editor
export EDITOR='vim'

# Quick navigation aliases
alias cdto='cd ~/git/tools'
alias cddo='cd ~/git/dotfiles'
alias b='cd ../'
alias x='exit'
alias cc='clear'
cdl() { cd "$a"; ls; }

# Enable Colors 🎨
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Git aliases
alias cdg='cd ~/git'
alias glog='git log --graph --pretty=format:"%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
alias gcm='git commit -m'
alias gch='git fetch && git checkout'
alias gb='git checkout -b'
alias gs='git status'
alias gclean='git branch --merged | egrep -v "(^\*|master|dev|main)" | xargs git branch -d'
alias gd='git diff'
alias gdd='git diff develop'
alias gp='git pull'
git config --global push.default current

gcam() {
    branch=$(git symbolic-ref --short HEAD)
    branch=${branch#*/}
    git add -A && git commit -m "$branch: $*"
}

# Useful scripts - see https://github.com/tylerjwoodfin
alias diary='python3 ~/git/tools/diary/main.py'
alias shorten='python3 ~/git/tools/shorten.py'
alias yt='python3 ~/git/tools/yt/main.py'
alias pitest='python3 ~/git/testfolder/test.py'
alias pibuild='python3 ~/git/tools/build/build.py'
alias turn='python3 ~/git/tools/kasalights/main.py'
alias notes='fff ~/syncthing/notes'
alias docs='fff ~/syncthing/docs'
alias work='fff ~/syncthing/work'
alias lofi='bash ~/git/tools/lofi.sh'
alias v='python3 ~/git/voicegpt/main.py'

# remindmail - see https://github.com/tylerjwoodfin/remindmail
rmmt() {
    remind -d tomorrow -m "$*"
}

rmmy() {
    remind --noconfirm -d now -m "$*"
}

rmmty() {
    remind -d tomorrow --noconfirm -m "$*"
}

alias rmm='remind'
alias rmmt='rmmt'
alias rmmy='rmmy'
alias rmmty='rmmty'
alias rmml='remind -ls'
alias rmmls='remind -ls'
alias rmme='remind --edit'
alias rmmlse='remind --edit'
alias rmmst='remind --show-tomorrow'
alias rmmsw='remind --show-week'
alias rmmj='remind --jira'
alias rmmti='remind -ti'
alias rmmtit='remind -ti --board Shopping --list-name Tyler'
alias rmmta='remind -ta'
alias rmmtai='remind -ta --board Shopping --list-name Tyler --item-name'
alias rmmtais='remind -ta --board Shopping --list-name Shared --item-name'

# Check weather
alias weather='curl wttr.in/?2QF'

[ -z "$PS1" ] && return

# Aliases below this line won't be called during interactive sessions (e.g., scripts)
